### ISSUE TITLE
.comm not supported

### ISSUE THREAD

**Issue by azertyfun** [Yamakaky/dcpu#8]
.comm is a linker-only instruction ; please add it to the ignore list.

Example: `.comm  driver_keyboard,11`

**Comment by Yamakaky** [comment]
Should I use the same semantic than `.lcomm` for my assembler?
http://web.mit.edu/gnu/doc/html/as_7.html

**Comment by azertyfun** [comment]
Uh, that's weird, `.comm` not generated anymore on cFrOSt, but I guess so?
